map_processor_node:
  ros__parameters:
    clearance_m: 0.35

open_coverage_path:
  ros__parameters:
    map_topic: /coverage/safe_map
    boundary_topic: /coverage/opennav_boundary
    wkt_topic: /coverage/opennav_wkt
    marker_topic: /coverage/opennav_polygons
    contour_simplification_px: 0.05
    min_region_area_m2: 0.20
    min_hole_area_m2: 0.02

f2c_path_gen_node:
  ros__parameters:
  # wkt for polygon from opennav, map for own extraction
    input_mode: wkt
    map_topic: /coverage/safe_map
    wkt_topic: /coverage/opennav_wkt
    path_topic: /coverage/path
    swath_marker_topic: /coverage/f2c_swaths
    robot_width_m: 0.2
    coverage_width_m: 0.2
    min_turning_radius_m: 0.1
    sweep_angle_rad: 0.0
    use_best_swath_angle: true
    swath_angle_step_rad: 0.10
    allow_overlap: false
    swath_objective: field_coverage
    path_output_mode: swaths
    path_step_m: 0.5
    contour_simplification_px: 0.5
    min_cell_area_m2: 0.2
    min_hole_area_m2: 0.02
    path_validation_step_m: 0.05
    repair_unsafe_connections: false
    allow_diagonal_repair: false

coverage_visualizer_node:
  ros__parameters: {}
